---
- name: loop
  hosts: csr
  gather_facts: no
  become: yes
  tasks:
    - name: Createloop
      ios_command:
        commands:
          - configure terminal
          - int lo 1
          - ip add 2.2.2.2 255.255.255.0
          - no shut
